[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
donaproto = "5HZRPHtJPhD5MvG1Sv71NwuiN5F51wXjnSQeey95chpA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/maksym/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/*"
