---
  name: Solana_Build
  
  on: [push]
  
  jobs:
    Test:
      runs-on: [ubuntu-22.04]
      env:
        RUST_VERSION: 1.77.0
        SOLANA_VERSION: 1.18.8

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: ${{ env.RUST_VERSION }}
            override: true
            components: rustfmt, clippy

        - name: Install Solana
          run: |
            sudo apt-get update
            sudo apt-get install -y libssl-dev libudev-dev zlib1g-dev llvm clang
            curl -sSf https://release.solana.com/v${{ env.SOLANA_VERSION }}/install | sh

        - name: Install Anchor
          run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 anchor-cli --locked

        - name: Build
          run: anchor build